- name: Install dependencies
  apt:
    cache_valid_time: 86400
    name: "{{ item }}"
  with_items:
    - zip
    - emacs
    - htop
    - tree
    - monit
    - default-jdk

- include: openjpeg.yml
- include: cantaloupe.yml
- include: apache2.yml
- include: monit.yml
  when: monit_install
