- name: Install dependencies
  apt:
    cache_valid_time: 86400
    name: zip

- name: Get cantaloupe source.
  unarchive:
    src: https://github.com/medusa-project/cantaloupe/releases/download/v{{ cantaloupe_version }}/Cantaloupe-{{ cantaloupe_version }}.zip
    dest: /opt/
    remote_src: yes


- name: Create the cantaloupe user account.
  user:
    name: cantaloupe
    home: /srv/home
    shell: /bin/false

- name: Make version agnostic symlink.
  file:
    src: "/opt/Cantaloupe-{{ cantaloupe_version }}"
    path: /opt/cantaloupe
    state: link
    owner: cantaloupe
    group: cantaloupe
    force: yes

- name: Make dirs for cantaloupe.  # per http://dev.digibess.it/doku.php?id=reloaded:is_cantsa
  file:
    path: "{{ item }}"
    state: directory
    owner: cantaloupe
    group: cantaloupe
    recurse: yes
  with_items:
    - /srv/cache
    - /srv/log
    - /srv/home
    - "/opt/Cantaloupe-{{ cantaloupe_version }}"

- name: Ensure cantaloupe settings.
  template:
    src: cantaloupe.properties.j2
    dest: /opt/cantaloupe/cantaloupe.properties
