---
- name: Get compilation tools.
  apt:
    name: "{{ item }}"
  with_items:
    - cmake
    - g++

- name: Remove any pre-existing version or link.
  file:
    path: /opt/openjpeg
    state: absent

- name: get OpenJPEG source.
  git:
    repo: https://github.com/uclouvain/openjpeg/
    dest: /opt/openjpeg
    version: "{{ openjpeg_version }}"
    force: yes

- name: Create build dir
  file:
    state: directory
    path: /opt/openjpeg/build

- name: Test for binaries.
  stat:
    path: /usr/local/bin/opj_compress
  register: opj_binaries

- name: Build.
  command: "{{ item }}"
  args:
    chdir: /opt/openjpeg/build
  with_items:
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - make install
    - make clean
  when: not opj_binaries.stat.exists
